name: Test PowerShell on Ubuntu
on: push

jobs:
  ps-test:
    name: Powershell test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform run on checkMovieSession file
        shell: pwsh
        run: |
          ./checkMovieStats.ps1
