name: Test PowerShell on Ubuntu
on:
  schedule:
    - cron: "0 6,8,10,12,13,14,15,16,17,18,19,20,21 * * *"
jobs:
  ps-test:
    name: Powershell test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform run on checkMovieSession file
        shell: pwsh
        env:
          githubtoken : ${{secrets.G_TOKEN }}
        run: |
          ./checkMovieStats.ps1
