name: Test PowerShell on Ubuntu
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  ps-test:
    name: Powershell test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform run on checkMovieSession file
        shell: pwsh
        env:
          githubtoken : ${{secrets.G_TOKEN }}
        run: |
          ./checkMovieStats.ps1
